# Generated by Django 4.0.3 on 2022-04-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('goal_amount', models.IntegerField()),
                ('end_date', models.DateTimeField()),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Productdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'productdetails',
            },
        ),
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_supporter', models.IntegerField()),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'products_users',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(through='products.ProductUser', to='users.user'),
        ),
    ]
