# Generated by Django 4.0.3 on 2022-04-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_sellers_product_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='total_supporter',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='total_supporter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
